version: '3'
services:
    jenkins:
        build:
            context: ./services/jenkins
            dockerfile: Dockerfile
        restart: always
        environment:
            JAVA_OPTS: -Dorg.apache.commons.jelly.tags.fmt.timeZone=Asia/Shanghai
        networks:
            - node-network
        ports:
            - "50000:50000"
            - "9001:8080"
        volumes:
            - ./app/jenkins:/var/jenkins_home
            - /home/pi/.ssh:/var/jenkins_home/.ssh

networks:
    node-network:
        driver: bridge